version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build and minify app
          command: gulp build
